import type { CatalogAdapter } from "../../types";

export const web = {
  beta: true,
  description:
    "Serve a browser chat UI from the same bot using the AI SDK useChat protocol \u2014 works out of the box with @ai-sdk/react and ai-elements.",
  env: {
    config: ["userName", "getUser", "persistMessageHistory", "threadIdFor"],
    notes:
      "The Web adapter delegates browser request authentication to the getUser config function.",
  },
  factoryExport: "createWebAdapter",
  features: {
    postMessage: "yes",
    editMessage: "no",
    deleteMessage: "no",
    fileUploads: "no",
    streaming: { status: "yes", label: "Native (SSE)" },
    scheduledMessages: "no",
    cardFormat: { status: "partial", label: "Markdown only (v1)" },
    buttons: "no",
    linkButtons: "no",
    selectMenus: "no",
    tables: { status: "yes", label: "GFM" },
    fields: "no",
    imagesInCards: "no",
    modals: "no",
    slashCommands: "no",
    mentions: "no",
    addReactions: "no",
    removeReactions: "no",
    typingIndicator: "no",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    customApiEndpoint: "yes",
    fetchMessages: { status: "partial", label: "State cache" },
    fetchThreadInfo: { status: "yes", label: "Synthesized" },
    fetchChannelMessages: { status: "partial", label: "State cache" },
    listThreads: "no",
    postChannelMessage: "no",
  },
  group: "official",
  icon: "web",
  name: "Web",
  packageName: "@chat-adapter/web",
  peerDeps: [],
  readme: "https://github.com/vercel/chat/tree/main/packages/adapter-web",
  slug: "web",
  type: "platform",
} as const satisfies CatalogAdapter;
