import { env, secretEnv, urlEnv } from "../../env";
import type { CatalogAdapter } from "../../types";

export const whatsapp = {
  beta: true,
  description:
    "Connect to WhatsApp Business Cloud for customer messaging and automated conversations.",
  env: {
    optional: [
      env("WHATSAPP_BOT_USERNAME", "Bot display name."),
      urlEnv("WHATSAPP_API_URL", "Override the WhatsApp Graph API URL."),
    ],
    required: [
      secretEnv("WHATSAPP_ACCESS_TOKEN", "Meta access token."),
      secretEnv("WHATSAPP_APP_SECRET", "App secret for webhook verification."),
      env("WHATSAPP_PHONE_NUMBER_ID", "Bot phone number ID."),
      secretEnv("WHATSAPP_VERIFY_TOKEN", "Webhook verification token."),
    ],
  },
  factoryExport: "createWhatsAppAdapter",
  features: {
    postMessage: "yes",
    messageReplies: { status: "partial", label: "Outbound only" },
    editMessage: "no",
    deleteMessage: "no",
    fileUploads: { status: "yes", label: "Images, audio, docs" },
    streaming: { status: "partial", label: "Buffered" },
    scheduledMessages: "no",
    cardFormat: { status: "partial", label: "Interactive messages" },
    buttons: { status: "yes", label: "Interactive replies" },
    linkButtons: { status: "partial", label: "Single CTA URL" },
    selectMenus: "no",
    tables: "no",
    fields: { status: "partial", label: "Formatted text" },
    imagesInCards: "yes",
    modals: "no",
    slashCommands: "no",
    mentions: "no",
    addReactions: "yes",
    removeReactions: "yes",
    typingIndicator: "yes",
    markAsRead: "yes",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    customApiEndpoint: "yes",
    fetchMessages: { status: "partial", label: "Cached sent only" },
    fetchSingleMessage: "no",
    fetchThreadInfo: "yes",
    fetchChannelMessages: "no",
    listThreads: "no",
    fetchChannelInfo: "no",
    postChannelMessage: "yes",
  },
  group: "official",
  icon: "whatsapp",
  name: "WhatsApp Business Cloud",
  packageName: "@chat-adapter/whatsapp",
  peerDeps: [],
  readme: "https://github.com/vercel/chat/tree/main/packages/adapter-whatsapp",
  slug: "whatsapp",
  type: "platform",
} as const satisfies CatalogAdapter;
