import type { CommunityAdapter } from "../../types";

export const baileys = {
  author: "rama-adi",
  description: "Chat SDK adapter for Baileys (Unofficial WhatsApp API).",
  features: {
    postMessage: "yes",
    editMessage: "yes",
    deleteMessage: "yes",
    fileUploads: "yes",
    streaming: "no",
    scheduledMessages: "no",
    cardFormat: "no",
    buttons: "no",
    linkButtons: "no",
    selectMenus: "no",
    tables: "no",
    fields: "no",
    imagesInCards: "no",
    modals: "no",
    slashCommands: "no",
    mentions: "yes",
    addReactions: "yes",
    removeReactions: "yes",
    typingIndicator: "yes",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    userLookup: "yes",
    customApiEndpoint: "no",
    fetchMessages: { status: "partial", label: "Empty unless you persist" },
    fetchSingleMessage: "no",
    fetchThreadInfo: "yes",
    fetchChannelMessages: {
      status: "partial",
      label: "Empty unless you persist",
    },
    listThreads: "no",
    fetchChannelInfo: "yes",
    postChannelMessage: "yes",
  },
  group: "community",
  name: "Baileys WhatsApp",
  packageName: "chat-adapter-baileys",
  readme:
    "https://github.com/rama-adi/chat-adapter-baileys/tree/b5454e7c04c75d91b06213f16a4af82ddb4a120f",
  slug: "baileys",
  type: "platform",
} as const satisfies CommunityAdapter;
