import type { CommunityAdapter } from "../../types";

export const blooio = {
  author: "midday-ai",
  description:
    "Blooio adapter for Chat SDK to send and receive iMessage, RCS, and SMS from your bot.",
  features: {
    postMessage: "yes",
    editMessage: "no",
    deleteMessage: "no",
    fileUploads: "yes",
    streaming: "no",
    scheduledMessages: "no",
    cardFormat: "no",
    buttons: "no",
    linkButtons: "no",
    selectMenus: "no",
    tables: "no",
    fields: "no",
    imagesInCards: "no",
    modals: "no",
    slashCommands: "no",
    mentions: "no",
    addReactions: { status: "yes", label: "Tapbacks" },
    removeReactions: { status: "yes", label: "Tapbacks" },
    typingIndicator: "yes",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    userLookup: { status: "yes", label: "checkCapabilities" },
    customApiEndpoint: { status: "yes", label: "baseUrl" },
    fetchMessages: "yes",
    fetchSingleMessage: "no",
    fetchThreadInfo: "yes",
    fetchChannelMessages: "yes",
    listThreads: "no",
    fetchChannelInfo: "yes",
    postChannelMessage: "yes",
  },
  group: "community",
  name: "Blooio iMessage",
  packageName: "chat-adapter-blooio",
  readme:
    "https://github.com/midday-ai/chat-adapter-blooio/tree/283678e3490275c7b440221ce3cdeac56bbfb60a",
  slug: "blooio",
  type: "platform",
} as const satisfies CommunityAdapter;
