import type { CommunityAdapter } from "../../types";

export const line = {
  author: "PunGrumpy",
  description:
    "Community LINE Messaging API adapter for Chat SDK with Flex Message cards, inbound media, action postbacks, and typing indicators.",
  features: {
    postMessage: "yes",
    editMessage: "no",
    deleteMessage: "no",
    fileUploads: { status: "partial", label: "Inbound only" },
    streaming: { status: "partial", label: "Buffered chunks" },
    scheduledMessages: "no",
    cardFormat: { status: "partial", label: "LINE Flex Messages" },
    buttons: { status: "partial", label: "Card postbacks" },
    linkButtons: "no",
    selectMenus: "no",
    tables: "no",
    fields: "no",
    imagesInCards: "no",
    modals: "no",
    slashCommands: "no",
    mentions: "yes",
    addReactions: "no",
    removeReactions: "no",
    typingIndicator: { status: "partial", label: "DMs only" },
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    userLookup: { status: "partial", label: "DM profiles" },
    customApiEndpoint: "no",
    fetchMessages: "no",
    fetchSingleMessage: "no",
    fetchThreadInfo: { status: "partial", label: "Users and groups" },
    fetchChannelMessages: "no",
    listThreads: "no",
    fetchChannelInfo: { status: "partial", label: "Group name" },
    postChannelMessage: "yes",
  },
  group: "community",
  name: "LINE",
  packageName: "chat-adapter-line",
  readme: "https://github.com/PunGrumpy/chat-adapter-line",
  slug: "line",
  type: "platform",
} as const satisfies CommunityAdapter;
