import type { CommunityAdapter } from "../../types";

export const mattermost = {
  author: "thiagoferolla",
  description:
    "Mattermost adapter for Chat SDK with support for posts, reactions, and slash commands.",
  features: {
    postMessage: "yes",
    editMessage: "yes",
    deleteMessage: "yes",
    fileUploads: { status: "partial", label: "No edit-with-uploads" },
    streaming: { status: "partial", label: "post+edit" },
    scheduledMessages: "no",
    cardFormat: { status: "partial", label: "Text fallback + actions" },
    buttons: { status: "partial", label: "Action attachments" },
    linkButtons: { status: "partial", label: "Action attachments" },
    selectMenus: { status: "partial", label: "Action attachments" },
    tables: "no",
    fields: "no",
    imagesInCards: { status: "partial", label: "Action attachments" },
    modals: "no",
    slashCommands: "no",
    mentions: "yes",
    addReactions: "yes",
    removeReactions: "yes",
    typingIndicator: "yes",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "yes",
    userLookup: "yes",
    customApiEndpoint: { status: "yes", label: "baseUrl" },
    fetchMessages: "yes",
    fetchSingleMessage: "yes",
    fetchThreadInfo: "yes",
    fetchChannelMessages: "yes",
    listThreads: "yes",
    fetchChannelInfo: "yes",
    postChannelMessage: "yes",
  },
  group: "community",
  name: "Mattermost",
  packageName: "chat-adapter-mattermost",
  readme:
    "https://github.com/thiagoferolla/chat-adapter-mattermost/tree/70eb85321cba65d511f6e158b9a2f5aac2aa922c",
  slug: "mattermost",
  type: "platform",
} as const satisfies CommunityAdapter;
