import type { CommunityAdapter } from "../../types";

export const qq = {
  author: "DemoMacro",
  description:
    "Community QQ Bot adapter for Chat SDK with WebSocket and webhook modes, multi-scene support (DM, group, text channel), and rich media.",
  features: {
    postMessage: "yes",
    editMessage: "no",
    deleteMessage: "no",
    fileUploads: "yes",
    streaming: "no",
    scheduledMessages: "no",
    cardFormat: "no",
    buttons: "no",
    linkButtons: "no",
    selectMenus: "no",
    tables: "no",
    fields: "no",
    imagesInCards: "no",
    modals: "no",
    slashCommands: "no",
    mentions: "no",
    addReactions: "no",
    removeReactions: "no",
    typingIndicator: "no",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    userLookup: "no",
    customApiEndpoint: "no",
    fetchMessages: "no",
    fetchSingleMessage: "no",
    fetchThreadInfo: "no",
    fetchChannelMessages: "no",
    listThreads: "no",
    fetchChannelInfo: "no",
    postChannelMessage: "no",
  },
  group: "community",
  name: "QQ Bot",
  packageName: "@agentor/chat-qq",
  readme:
    "https://github.com/DemoMacro/agentor/tree/6248fcc6b09821cfc2fb7bc50ef16eec1526e756/packages/chat-qq",
  slug: "qq",
  type: "platform",
} as const satisfies CommunityAdapter;
