import type { CommunityAdapter } from "../../types";

export const webex = {
  author: "SebastianBodza",
  description:
    "Community Webex adapter for Chat SDK with support for spaces, threads, and adaptive cards.",
  features: {
    postMessage: "yes",
    editMessage: { status: "partial", label: "Not with files" },
    deleteMessage: "yes",
    fileUploads: { status: "partial", label: "1 file per message" },
    streaming: { status: "partial", label: "post+edit" },
    scheduledMessages: "no",
    cardFormat: { status: "yes", label: "Adaptive Cards" },
    buttons: "yes",
    linkButtons: "yes",
    selectMenus: "yes",
    tables: "no",
    fields: "yes",
    imagesInCards: "yes",
    modals: "yes",
    slashCommands: "no",
    mentions: "yes",
    addReactions: "no",
    removeReactions: "no",
    typingIndicator: "no",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    userLookup: "yes",
    customApiEndpoint: { status: "yes", label: "baseUrl" },
    fetchMessages: "yes",
    fetchSingleMessage: "yes",
    fetchThreadInfo: "yes",
    fetchChannelMessages: "yes",
    listThreads: "yes",
    fetchChannelInfo: "yes",
    postChannelMessage: "yes",
  },
  group: "community",
  name: "Webex",
  packageName: "@bitbasti/chat-adapter-webex",
  readme:
    "https://github.com/SebastianBodza/chat-adapter-webex/tree/982d76b24217dfe2e248ec13a17d16c2df32e09e",
  slug: "webex",
  type: "platform",
} as const satisfies CommunityAdapter;
