import type { CommunityAdapter } from "../../types";

export const wecom = {
  author: "DemoMacro",
  description:
    "Community WeCom (企业微信) adapter for Chat SDK covering group webhook bots, smart bots, and apps, with template cards and AES encryption.",
  features: {
    postMessage: "yes",
    editMessage: "no",
    deleteMessage: { status: "partial", label: "App adapter only" },
    fileUploads: "yes",
    streaming: "no",
    scheduledMessages: "no",
    cardFormat: "yes",
    buttons: "yes",
    linkButtons: "no",
    selectMenus: {
      status: "partial",
      label: "Template card dropdown (multiple_interaction)",
    },
    tables: "no",
    fields: "yes",
    imagesInCards: "yes",
    modals: "no",
    slashCommands: "no",
    mentions: { status: "partial", label: "App adapter (@mentioned_list)" },
    addReactions: "no",
    removeReactions: "no",
    typingIndicator: "no",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    userLookup: "no",
    customApiEndpoint: "no",
    fetchMessages: "no",
    fetchSingleMessage: "no",
    fetchThreadInfo: "no",
    fetchChannelMessages: "no",
    listThreads: "no",
    fetchChannelInfo: "no",
    postChannelMessage: "no",
  },
  group: "community",
  name: "WeCom",
  packageName: "@agentor/chat-wecom",
  readme:
    "https://github.com/DemoMacro/agentor/tree/6248fcc6b09821cfc2fb7bc50ef16eec1526e756/packages/chat-wecom",
  slug: "wecom",
  type: "platform",
} as const satisfies CommunityAdapter;
