import type { CommunityAdapter } from "../../types";

export const weixin = {
  author: "wong2",
  description:
    "Community Weixin (WeChat) iLink bot adapter for Chat SDK with long polling, QR login, media uploads, and typing indicators.",
  features: {
    postMessage: "yes",
    editMessage: "no",
    deleteMessage: "no",
    fileUploads: "yes",
    streaming: "no",
    scheduledMessages: "no",
    cardFormat: "no",
    buttons: "no",
    linkButtons: "no",
    selectMenus: "no",
    tables: "no",
    fields: "no",
    imagesInCards: "no",
    modals: "no",
    slashCommands: "no",
    mentions: "no",
    addReactions: "no",
    removeReactions: "no",
    typingIndicator: "yes",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    userLookup: "no",
    customApiEndpoint: { status: "yes", label: "baseUrl" },
    fetchMessages: "no",
    fetchSingleMessage: "no",
    fetchThreadInfo: "yes",
    fetchChannelMessages: "no",
    listThreads: "no",
    fetchChannelInfo: "no",
    postChannelMessage: "no",
  },
  group: "community",
  name: "Weixin",
  packageName: "chat-adapter-weixin",
  readme:
    "https://github.com/wong2/weixin-chat-adapter/tree/62a2b42a26b48f731ef585114017669fccf95ca5",
  slug: "weixin",
  type: "platform",
} as const satisfies CommunityAdapter;
