import type { CommunityAdapter } from "../../types";

export const zaileys = {
  author: "zeative",
  description:
    "WhatsApp adapter powered by Zaileys — real message history, native buttons from Cards, decrypted poll votes, and scheduling.",
  features: {
    postMessage: "yes",
    editMessage: "yes",
    deleteMessage: "yes",
    fileUploads: "yes",
    streaming: { status: "partial", label: "Post + edit fallback" },
    scheduledMessages: "yes",
    cardFormat: { status: "partial", label: "Buttons native, body as text" },
    buttons: "yes",
    linkButtons: "no",
    selectMenus: "no",
    tables: "no",
    fields: "no",
    imagesInCards: { status: "partial", label: "Header image only" },
    modals: "no",
    slashCommands: { status: "partial", label: "Opt-in prefix routing" },
    mentions: "yes",
    addReactions: "yes",
    removeReactions: "yes",
    typingIndicator: "yes",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    userLookup: "yes",
    customApiEndpoint: "no",
    fetchMessages: { status: "yes", label: "Via the Zaileys store" },
    fetchSingleMessage: "yes",
    fetchThreadInfo: "yes",
    fetchChannelMessages: { status: "yes", label: "Same as fetchMessages" },
    listThreads: "no",
    fetchChannelInfo: "yes",
    postChannelMessage: "yes",
  },
  group: "community",
  name: "Zaileys WhatsApp",
  packageName: "chat-adapter-zaileys",
  readme:
    "https://github.com/zeative/chat-adapter-zaileys/tree/104a2a631422e60972b8f63ec115bc7a399a2494",
  slug: "zaileys",
  type: "platform",
} as const satisfies CommunityAdapter;
