import type { CommunityAdapter } from "../../types";

export const zalo = {
  author: "buiducnhat",
  description:
    "Zalo adapter for Chat SDK using Zalo for building your own Zalo bots.",
  features: {
    postMessage: "yes",
    editMessage: "no",
    deleteMessage: "no",
    fileUploads: { status: "partial", label: "Inbound only" },
    streaming: { status: "partial", label: "Buffered" },
    scheduledMessages: "no",
    cardFormat: "no",
    buttons: "no",
    linkButtons: "no",
    selectMenus: "no",
    tables: "no",
    fields: "no",
    imagesInCards: "no",
    modals: "no",
    slashCommands: "no",
    mentions: "no",
    addReactions: "no",
    removeReactions: "no",
    typingIndicator: "yes",
    messageUpdatedEvents: "no",
    messageDeletedEvents: "no",
    directMessages: "yes",
    ephemeralMessages: "no",
    userLookup: "no",
    customApiEndpoint: "no",
    fetchMessages: "no",
    fetchSingleMessage: "no",
    fetchThreadInfo: "yes",
    fetchChannelMessages: "no",
    listThreads: "no",
    fetchChannelInfo: "yes",
    postChannelMessage: "yes",
  },
  group: "community",
  name: "Zalo",
  packageName: "chat-adapter-zalo",
  readme:
    "https://github.com/buiducnhat/chat-adapter-zalo/tree/a11acb91efa9752c6d15c0a00c759b92c479e6fa",
  slug: "zalo",
  type: "platform",
} as const satisfies CommunityAdapter;
